### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by anupamjamatia** [GreyMatter7/Hindi-ULMFiT#1]
Hi, May I get the dataset to run the code please

**Comment by GreyMatter7** [comment]
Hey Anupam, sorry we can’t share the dataset with you currently as it is confidential. However if you want to try out ULMFiT for Hindi text classification you can try it out on this dataset https://github.com/goru001/nlp-for-hindi/tree/master/datasets-preparation/hindi-movie-review-dataset.
